### ISSUE TITLE
support macos-14 in CI

### ISSUE THREAD

**Issue by RyosukeCla** [plaidev/nativebrik-sdk#1]
```
on:
  push:
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: XCTest
        run: xcodebuild test -project ./ios/Nativebrik/Nativebrik.xcodeproj -scheme NativebrikTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2'

```
